### ISSUE TITLE
preloader appearing late

### ISSUE THREAD

**Issue by vlrprbttst** [niklausgerber/PreLoadMe#7]
hi nik! thanks for the preloader. I used it on a couple of projects, but in one in particular it appears a split second too late making the use of the preloader.. useless :) i used the preloader to mask the DOM while it paints but if the preloader appears too late there's no sense in using it. I've tried two preloaders on this particular project and i always get it appearing too late. could you help with this issue? why is it apearing late?

live project: www.valeriopierbattista.com/cv
the code (index file): https://github.com/vlrprbttst/valeriopierbattista-cv/blob/master/html/index.html

thanks for your time!

**Comment by niklausgerber** [comment]
First of all you must place the loader directly after the body. You have different things before which will be rendered first. Did you try that?

**Comment by vlrprbttst** [comment]
yes.. same problem still :/ that div right after the body tag was a div set to display none, he's was not appearing anyway. i have no idea why this is happening
