### ISSUE TITLE
Does not work with later JQuery version

### ISSUE THREAD

**Issue by sommmen** [niklausgerber/PreLoadMe#9]
`        
              <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> `

This does not work, hower version 1.6 does work.

**Comment by sommmen** [comment]
google however provided a solution:
http://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error

so:

`//<![CDATA[
		$(window).on('load', function() { // makes sure the whole site is loaded
			$('#status').fadeOut(); // will first fade out the loading animation
			$('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
			$('body').delay(350).css({'overflow':'visible'});
		})
	//]]>`

works with JQ version > 3

**Comment by niklausgerber** [comment]
Thank you @sommmen for your research. I am just uploading the fix.
